Updated bin/ and nvim/  Changes to be committed: 	modified:   bin/colorscheme 	modified:   bin/dotfetch 	modified:   bin/dt 	deleted:    bin/pickvideo 	modified:   bin/pickwp 	modified:   bin/pots 	modified:   glava/radial.glsl 	modified:   i3/config 	modified:   install.sh 	modified:   nvim/init.lua 	modified:   nvim/keybindings.lua 	modified:   nvim/pkg/coc.lua 	deleted:    nvim/pkg/colorscheme.lua 	new file:   nvim/pkg/lline.lua 	new file:   nvim/pkg/sr.lua 	new file:   nvim/pkg/tsitter.lua 	modified:   nvim/plugins.lua 	modified:   polybar/scripts/dnfupdate

diff --git a/bin/pots b/bin/pots
--- a/bin/pots
+++ b/bin/pots
@@ -4,7 +4,7 @@
 #  Displays a random program in the /bin directory that has ${man}
 # and ${whatis}
 
-PrintPots() {
+Print() {
     line="$cmd\e[;0m${cmd_info//$cmd/}\e[36;1m"
     line_count=$((`echo $line | wc -m ` -13 )) 
     echo -e "\e[36;1m┌`seq -s─ $line_count | tr -d '[:digit:]'`┐"
@@ -15,13 +15,13 @@ PrintPots() {
 for arg in $@;do
     cmd=$arg
     cmd_info=`whatis $cmd 2> /dev/null`
-    [ "$cmd_info" = "" ] && `echo -e "Error: No such file or directory." 1>&2` || PrintPots
+    [ $cmd_info = ] && `echo -e "Error: No such file or directory." 1>&2` || Print
 done
 
-if [ "$cmd" = "" ]; then
+if [ $cmd = ]; then
     while [ "$cmd_info" = "" ]; do
         cmd="`ls /bin/ | shuf -n 1`"
         cmd_info=`whatis $cmd 2> /dev/null`
     done
-    PrintPots
+    Print
 fi
